-- csv rows structure
--CIS	DENOMINATION	FORME_PHARMACEUTIQUE	VOIES_ADMINISTRATION	STATU_AMM	TYPE_AMM	ETAT_COMMERCIALISATION	DATE_AMM	STATUT_BDM	AUTORISATION_EUROPEENE	TITULAIRES	SURVEILLANCE_RENFORCEE


-- .import CIS_bdpm.txt CIS_BDPM
CREATE TABLE CIS_BDPM(
  CIS VARCHAR(255) PRIMARY KEY,
  DENOMINATION VARCHAR(255) ,
  FORME_PHARMACEUTIQUE VARCHAR(255) ,
  VOIES_ADMINISTRATION VARCHAR(255) ,
  STATU_AMM VARCHAR(255) ,
  TYPE_AMM VARCHAR(255) ,
  ETAT_COMMERCIALISATION VARCHAR(255) ,
  DATE_AMM DATE ,
  STATUT_BDM VARCHAR(255) ,
  AUTORISATION_EUROPEENE VARCHAR(255) ,
  TITULAIRES VARCHAR(255) ,
  SURVEILLANCE_RENFORCEE VARCHAR(255)
);

-- csv rows structure
-- CIS	CIP7	LIBELLE_PRESENTATION	STATUT_ADMIM_PRESENTATION	ETAT_COMMERCIALISATION_AMM	DATE_DECLARATiON_COMMERCIALISATION	CIP13	AGREMENT_COLLECTIVITES	TAUX_REMBOURSEMENT	PRIX_EURO	INDICATION_REMBOURSEMENT_ASSURANCE
-- .import CIS_CIP_bdpm.txt CIS_CIP_BDPM
CREATE TABLE CIS_CIP_BDPM(
  CIS  VARCHAR(255),
  CIP7 VARCHAR(255),
  LIBELLE_PRESENTATION VARCHAR(255),
  STATUT_ADMIM_PRESENTATION VARCHAR(255),
  ETAT_COMMERCIALISATION_AMM VARCHAR(255),
  DATE_DECLARATiON_COMMERCIALISATION DATE,
  CIP13 VARCHAR(255),
  AGREMENT_COLLECTIVITES VARCHAR(255),
  TAUX_REMBOURSEMENT STRING  VARCHAR(255),
  PRIX_EURO VARCHAR(255),
  INDICATION_REMBOURSEMENT_ASSURANCE VARCHAR(255),
  FOREIGN KEY(CIS) REFERENCES CIS_BDPM(CIS)
);

CREATE INDEX CIS_CIP13_BDPM_INDEX ON CIS_CIP_BDPM ( CIP13 );
CREATE INDEX CIS_CIP7_BDPM_INDEX ON CIS_CIP_BDPM ( CIP7 );

-- csv rows structure
-- CIS	DESIGNATION_ELEMENT_PHARMA	CODE_SUBSTANCE	DENOMINATION_SUBSTANCE	DOSAGE_SUBSTANCE	REFERENCE_DOSAGE	NATURE_COMPOSITION	NUMERO_LIAISON_SA_FT
-- .import CIS_COMPO_bdpm.txt CIS_COMPOSITION_BDPM
CREATE TABLE CIS_COMPOSITION_BDPM(
  CIS VARCHAR(255),
  DESIGNATION_ELEMENT_PHARMA VARCHAR(255),
  CODE_SUBSTANCE VARCHAR(255),
  DENOMINATION_SUBSTANCE VARCHAR(255),
  DOSAGE_SUBSTANCE VARCHAR(255),
  REFERENCE_DOSAGE VARCHAR(255),
  NATURE_COMPOSITION VARCHAR(255),
  NUMERO_LIAISON_SA_FT VARCHAR(255),
  FOREIGN KEY(CIS) REFERENCES CIS_BDPM(CIS)
);
